services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sniffydb
    volumes:
      - ./db-data_local/:/var/lib/postgresql/data/

volumes:
  postgres:
